version: '3.5'

services:
  database:
    image: postgres:14.1
    container_name: study_database
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      
  backend:
    build: ./backend
    container_name: study_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/backend/
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: postgresql://postgres:postgres@database:5432/postgres
    depends_on:
      - database

  frontend:
    build: ./frontend
    container_name: study_frontend
    env_file:
      - ./.env
    volumes:
      - ./frontend:/frontend/
    ports:
      - "4200:4200"

  gateway:
    build: ./gateway
    container_name: study_gateway
    env_file:
      - ./.env
    ports:
      - 8080:80
    depends_on:
      - frontend
      - backend

volumes:
  db_data:
